"""add_admin_role_to_users

Revision ID: 63206a3545a2
Revises: 8fdedcc12cfa
Create Date: 2025-06-23 15:12:09.442545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63206a3545a2'
down_revision = '8fdedcc12cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_stories', schema=None) as batch_op:
        batch_op.drop_index('ix_audio_stories_elevenlabs_voice_id')
        batch_op.drop_index('ix_audio_stories_status')
        batch_op.drop_index('ix_audio_stories_story_id')
        batch_op.drop_index('ix_audio_stories_story_voice')
        batch_op.drop_index('ix_audio_stories_user_id')
        batch_op.drop_index('ix_audio_stories_voice_id')
        batch_op.drop_column('elevenlabs_voice_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('voices', schema=None) as batch_op:
        batch_op.drop_index('ix_voices_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voices', schema=None) as batch_op:
        batch_op.create_index('ix_voices_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('audio_stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elevenlabs_voice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_index('ix_audio_stories_voice_id', ['voice_id'], unique=False)
        batch_op.create_index('ix_audio_stories_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_audio_stories_story_voice', ['story_id', 'voice_id'], unique=True)
        batch_op.create_index('ix_audio_stories_story_id', ['story_id'], unique=False)
        batch_op.create_index('ix_audio_stories_status', ['status'], unique=False)
        batch_op.create_index('ix_audio_stories_elevenlabs_voice_id', ['elevenlabs_voice_id'], unique=False)

    # ### end Alembic commands ###
